var geoip = require('geoip-lite');

var countryCodeToName = {
	"DZ" : "Algeria",
	"BD" : "Bangladesh",
	"CL" : "Chile",
	"CN" : "China",
	"CO" : "Colombia",
	"EG" : "Egypt",
	"HK" : "Hong Kong",
	"IN" : "India",
	"ID" : "Indonesia",
	"JO" : "Jordan",
	"MY" : "Malaysia",
	"MX" : "Mexico",
	"MA" : "Morocco",
	"NP" : "Nepal",
	"NG" : "Nigeria",
	"PK" : "Pakistan",
	"PE" : "Peru",
	"PH" : "Philippines",
	"RU" : "Russian Federation",
	"SG" : "Singapore",
	"ZA" : "South Africa",
	"TW" : "Taiwan",
	"TH" : "Thailand",
	"TN" : "Tunisia",
	"UA" : "Ukraine",
	"VE" : "Venezuela",
	"VN" : "Vietnam",
	"DE" : "Germany",
	"AT" : "Austria",
	"CH" : "Switzerland",
	"WW" : "All of the World",
	"FR" : "France",
	"IT" : "Italy",
	"ES" : "Spain",
	"SE" : "Sweden",
	"BE" : "Belgium",
	"DK" : "Denmark",
	"FI" : "Finland",
	"GR" : "Greece",
	"HU" : "Hungary",
	"IS" : "Iceland",
	"IE" : "Ireland",
	"LI" : "Liechtenstein",
	"LU" : "Luxembourg",
	"NL" : "Netherlands",
	"NO" : "Norway",
	"PL" : "Poland",
	"PT" : "Portugal",
	"TR" : "Turkey",
	"BA" : "Bosnia and Herzegovina",
	"BG" : "Bulgaria",
	"HR" : "Croatia",
	"CZ" : "Czech Republic",
	"EE" : "Estonia",
	"LV" : "Latvia",
	"LT" : "Lithuania",
	"RO" : "Romania",
	"SK" : "Slovakia",
	"SI" : "Slovenia",
	"GB" : "United Kingdom",
	"YU" : "Yugoslavia",
	"RS" : "Serbia",
	"CA" : "Canada",
	"US" : "United States",
	"BR" : "Brazil",
	"AR" : "Argentina",
	"AU" : "Australia",
	"EC" : "Ecuador",
	"IL" : "Israel",
	"JP" : "Japan",
	"KR" : "Korea, Republic of",
	"NZ" : "New Zealand",
	"SA" : "Saudi Arabia",
	"AE" : "United Arab Emirates",
	"UY" : "Uruguay",
	"BO" : "Bolivia",
	"CR" : "Costa Rica",
	"DO" : "Dominican Republic",
	"SV" : "El Salvador",
	"GT" : "Guatemala",
	"JM" : "Jamaica",
	"PA" : "Panama",
	"PY" : "Paraguay",
	"PR" : "Puerto Rico",
	"TT" : "Trinidad and Tobago",
	"KW" : "Kuwait",
	"AF" : "Afghanistan",
	"AL" : "Albania",
	"AS" : "American Samoa",
	"AD" : "Andorra",
	"AO" : "Angola",
	"AI" : "Anguilla",
	"AG" : "Antigua and Barbuda",
	"AM" : "Armenia",
	"AW" : "Aruba",
	"AP" : "Asia/Pacific Region",
	"AZ" : "Azerbaijan",
	"BS" : "Bahamas",
	"BH" : "Bahrain",
	"BB" : "Barbados",
	"BY" : "Belarus",
	"BZ" : "Belize",
	"BJ" : "Benin",
	"BM" : "Bermuda",
	"BT" : "Bhutan",
	"BW" : "Botswana",
	"BV" : "Bouvet Island",
	"IO" : "British Indian Ocean Territory",
	"BN" : "Brunei Darussalam",
	"BF" : "Burkina Faso",
	"BI" : "Burundi",
	"KH" : "Cambodia",
	"CM" : "Cameroon",
	"CV" : "Cape Verde",
	"KY" : "Cayman Islands",
	"CF" : "Central African Republic",
	"TD" : "Chad",
	"KM" : "Comoros",
	"CG" : "Congo",
	"CD" : "Congo, The Democratic Republic of the",
	"CK" : "Cook Islands",
	"CI" : "Cote D&#039;Ivoire",
	"CU" : "Cuba",
	"CY" : "Cyprus",
	"DJ" : "Djibouti",
	"DM" : "Dominica",
	"GQ" : "Equatorial Guinea",
	"ER" : "Eritrea",
	"ET" : "Ethiopia",
	"EU" : "Europe",
	"FK" : "Falkland Islands (Malvinas)",
	"FO" : "Faroe Islands",
	"FJ" : "Fiji",
	"GF" : "French Guiana",
	"PF" : "French Polynesia",
	"TF" : "French Southern Territories",
	"GA" : "Gabon",
	"GM" : "Gambia",
	"GE" : "Georgia",
	"GH" : "Ghana",
	"GI" : "Gibraltar",
	"GL" : "Greenland",
	"GD" : "Grenada",
	"GP" : "Guadeloupe",
	"GU" : "Guam",
	"GN" : "Guinea",
	"GW" : "Guinea-Bissau",
	"GY" : "Guyana",
	"HT" : "Haiti",
	"HM" : "Heard Island and McDonald Islands",
	"VA" : "Holy See (Vatican City State)",
	"HN" : "Honduras",
	"IR" : "Iran, Islamic Republic of",
	"IQ" : "Iraq",
	"KZ" : "Kazakstan",
	"KE" : "Kenya",
	"KI" : "Kiribati",
	"KP" : "Korea, Democratic People&#039;s Republic of",
	"KG" : "Kyrgyzstan",
	"LA" : "Lao People&#039;s Democratic Republic",
	"LB" : "Lebanon",
	"LS" : "Lesotho",
	"LR" : "Liberia",
	"LY" : "Libyan Arab Jamahiriya",
	"MO" : "Macau",
	"MK" : "Macedonia",
	"MG" : "Madagascar",
	"MW" : "Malawi",
	"MV" : "Maldives",
	"ML" : "Mali",
	"MT" : "Malta",
	"MH" : "Marshall Islands",
	"MQ" : "Martinique",
	"MR" : "Mauritania",
	"MU" : "Mauritius",
	"YT" : "Mayotte",
	"FM" : "Micronesia, Federated States of",
	"MD" : "Moldova, Republic of",
	"MC" : "Monaco",
	"MN" : "Mongolia",
	"MS" : "Montserrat",
	"MZ" : "Mozambique",
	"NA" : "Namibia",
	"NR" : "Nauru",
	"AN" : "Netherlands Antilles",
	"NC" : "New Caledonia",
	"NI" : "Nicaragua",
	"NE" : "Niger",
	"NU" : "Niue",
	"NF" : "Norfolk Island",
	"MP" : "Northern Mariana Islands",
	"OM" : "Oman",
	"PW" : "Palau",
	"PS" : "Palestinian Territory, Occupied",
	"PG" : "Papua New Guinea",
	"QA" : "Qatar",
	"RE" : "Reunion",
	"RW" : "Rwanda",
	"KN" : "Saint Kitts and Nevis",
	"LC" : "Saint Lucia",
	"VC" : "Saint Vincent and the Grenadines",
	"WS" : "Samoa",
	"SM" : "San Marino",
	"ST" : "Sao Tome and Principe",
	"A2" : "Satellite Provider",
	"SN" : "Senegal",
	"SC" : "Seychelles",
	"SL" : "Sierra Leone",
	"SB" : "Solomon Islands",
	"SO" : "Somalia",
	"LK" : "Sri Lanka",
	"SD" : "Sudan",
	"SR" : "Suriname",
	"SZ" : "Swaziland",
	"SY" : "Syrian Arab Republic",
	"TJ" : "Tajikistan",
	"TZ" : "Tanzania, United Republic of",
	"TG" : "Togo",
	"TK" : "Tokelau",
	"TO" : "Tonga",
	"TM" : "Turkmenistan",
	"TC" : "Turks and Caicos Islands",
	"TV" : "Tuvalu",
	"UG" : "Uganda",
	"UM" : "United States Minor Outlying Islands",
	"undefined" : "Unknown",
	"UZ" : "Uzbekistan",
	"VU" : "Vanuatu",
	"VG" : "Virgin Islands, British",
	"WF" : "Wallis and Futuna",
	"YE" : "Yemen",
	"ZM" : "Zambia",
	"ZW" : "Zimbabwe",
	"VI" : "Virgin Islands, U.S.",
	"ME" : "Montenegro",
	"IM" : "Isle Of Man",
	"GG" : "Guernsey",
	"JE" : "Jersey",
	"MM" : "Myanmar",
	"AX" : "Aland Islands",
	"MF" : "Saint Martin",
	"PM" : "Saint Pierre and Miquelon",
	"CW" : "Cook Islands"
};

var countryCodeToContinent = {
	"DZ" : "Africa",
	"BD" : "Asia",
	"CL" : "South America",
	"CN" : "Asia",
	"CO" : "South America",
	"EG" : "Africa",
	"HK" : "Asia",
	"IN" : "Asia",
	"ID" : "Asia",
	"JO" : "Asia",
	"MY" : "Asia",
	"MX" : "North America",
	"MA" : "Africa",
	"NP" : "Asia",
	"NG" : "Africa",
	"PK" : "Asia",
	"PE" : "South America",
	"PH" : "Asia",
	"RU" : "Europe",
	"SG" : "Asia",
	"ZA" : "Africa",
	"TW" : "Asia",
	"TH" : "Asia",
	"TN" : "Africa",
	"UA" : "Europe",
	"VE" : "South America",
	"VN" : "Asia",
	"DE" : "Europe",
	"AT" : "Europe",
	"CH" : "Europe",
	"WW" : "",
	"FR" : "Europe",
	"IT" : "Europe",
	"ES" : "Europe",
	"SE" : "Europe",
	"BE" : "Europe",
	"DK" : "Europe",
	"FI" : "Europe",
	"GR" : "Europe",
	"HU" : "Europe",
	"IS" : "Europe",
	"IE" : "Europe",
	"LI" : "Europe",
	"LU" : "Europe",
	"NL" : "Europe",
	"NO" : "Europe",
	"PL" : "Europe",
	"PT" : "Europe",
	"TR" : "Europe",
	"BA" : "Europe",
	"BG" : "Europe",
	"HR" : "Europe",
	"CZ" : "Europe",
	"EE" : "Europe",
	"LV" : "Europe",
	"LT" : "Europe",
	"RO" : "Europe",
	"SK" : "Europe",
	"SI" : "Europe",
	"GB" : "Europe",
	"YU" : "Europe",
	"RS" : "Europe",
	"CA" : "North America",
	"US" : "North America",
	"BR" : "South America",
	"AR" : "South America",
	"AU" : "Oceania and Austraila",
	"EC" : "South America",
	"IL" : "Asia",
	"JP" : "Asia",
	"KR" : "Asia",
	"NZ" : "Oceania and Austraila",
	"SA" : "Asia",
	"AE" : "Asia",
	"UY" : "South America",
	"BO" : "South America",
	"CR" : "South America",
	"DO" : "South America",
	"SV" : "South America",
	"GT" : "South America",
	"JM" : "South America",
	"PA" : "South America",
	"PY" : "South America",
	"PR" : "South America",
	"TT" : "South America",
	"KW" : "Asia",
	"AF" : "Asia",
	"AL" : "Europe",
	"AS" : "Oceania and Austraila",
	"AD" : "Europe",
	"AO" : "Africa",
	"AI" : "South America",
	"AG" : "South America",
	"AM" : "Asia",
	"AW" : "South America",
	"AP" : "Asia",
	"AZ" : "Asia",
	"BS" : "South America",
	"BH" : "Asia",
	"BB" : "South America",
	"BY" : "Europe",
	"BZ" : "South America",
	"BJ" : "Africa",
	"BM" : "South America",
	"BT" : "Asia",
	"BW" : "Africa",
	"BV" : "Africa",
	"IO" : "Asia",
	"BN" : "Asia",
	"BF" : "Africa",
	"BI" : "Africa",
	"KH" : "Asia",
	"CM" : "Africa",
	"CV" : "Africa",
	"KY" : "South America",
	"CF" : "Africa",
	"TD" : "Africa",
	"KM" : "Africa",
	"CG" : "Africa",
	"CD" : "Africa",
	"CK" : "Oceania and Austraila",
	"CI" : "Africa",
	"CU" : "South America",
	"CY" : "Asia",
	"DJ" : "Africa",
	"DM" : "South America",
	"GQ" : "Africa",
	"ER" : "Africa",
	"ET" : "Africa",
	"EU" : "Europe",
	"FK" : "South America",
	"FO" : "Europe",
	"FJ" : "Oceania and Austraila",
	"GF" : "South America",
	"PF" : "Oceania and Austraila",
	"TF" : "Africa",
	"GA" : "Africa",
	"GM" : "Africa",
	"GE" : "Asia",
	"GH" : "Africa",
	"GI" : "Europe",
	"GL" : "South America",
	"GD" : "South America",
	"GP" : "South America",
	"GU" : "Oceania and Austraila",
	"GN" : "Africa",
	"GW" : "Africa",
	"GY" : "South America",
	"HT" : "South America",
	"HM" : "Africa",
	"VA" : "Europe",
	"HN" : "South America",
	"IR" : "Asia",
	"IQ" : "Asia",
	"KZ" : "Asia",
	"KE" : "Africa",
	"KI" : "Oceania and Austraila",
	"KP" : "Asia",
	"KG" : "Asia",
	"LA" : "Asia",
	"LB" : "Asia",
	"LS" : "Africa",
	"LR" : "Africa",
	"LY" : "Africa",
	"MO" : "Asia",
	"MK" : "Europe",
	"MG" : "Africa",
	"MW" : "Africa",
	"MV" : "Asia",
	"ML" : "Africa",
	"MT" : "Europe",
	"MH" : "Oceania and Austraila",
	"MQ" : "South America",
	"MR" : "Africa",
	"MU" : "Africa",
	"YT" : "Africa",
	"FM" : "Oceania and Austraila",
	"MD" : "Europe",
	"MC" : "Europe",
	"MN" : "Asia",
	"MS" : "South America",
	"MZ" : "Africa",
	"NA" : "Africa",
	"NR" : "Oceania and Austraila",
	"AN" : "South America",
	"NC" : "Oceania and Austraila",
	"NI" : "South America",
	"NE" : "Africa",
	"NU" : "Oceania and Austraila",
	"NF" : "Oceania and Austraila",
	"MP" : "Oceania and Austraila",
	"OM" : "Asia",
	"PW" : "Oceania and Austraila",
	"PS" : "Asia",
	"PG" : "Oceania and Austraila",
	"QA" : "Asia",
	"RE" : "Africa",
	"RW" : "Africa",
	"KN" : "South America",
	"LC" : "South America",
	"VC" : "South America",
	"WS" : "Oceania and Austraila",
	"SM" : "Europe",
	"ST" : "Africa",
	"A2" : "",
	"SN" : "Africa",
	"SC" : "Africa",
	"SL" : "Africa",
	"SB" : "Oceania and Austraila",
	"SO" : "Africa",
	"LK" : "Asia",
	"SD" : "Africa",
	"SR" : "South America",
	"SZ" : "Africa",
	"SY" : "Asia",
	"TJ" : "Asia",
	"TZ" : "Africa",
	"TG" : "Africa",
	"TK" : "Oceania and Austraila",
	"TO" : "Oceania and Austraila",
	"TM" : "Asia",
	"TC" : "South America",
	"TV" : "Oceania and Austraila",
	"UG" : "Africa",
	"UM" : "Oceania and Austraila",
	"undefined" : "",
	"UZ" : "Asia",
	"VU" : "Oceania and Austraila",
	"VG" : "South America",
	"WF" : "Oceania and Austraila",
	"YE" : "Asia",
	"ZM" : "Africa",
	"ZW" : "Africa",
	"VI" : "South America",
	"ME" : "Africa",
	"IM" : "Europe",
	"GG" : "Europe",
	"JE" : "Europe",
	"MM" : "Asia",
	"AX" : "Europe",
	"MF" : "South America",
	"PM" : "North America",
	"CW" : "Asia"
};

exports.geoip = function() {
  return function(req, res, next) {
    var ip = getClientIp(req);
    req.geoip = {};

    var lookup = geoip.lookup(ip);
    req.geoip.city = 'unknown';
    req.geoip.region = 'unknown';
    req.geoip.ll = [];
    req.geoip.country = {
      country_code: '--',
      country_name: 'unknown',
      continent: 'unknown'
    };

    if( lookup ) {
      req.geoip.city = lookup.city;
      req.geoip.region = lookup.region;
      req.geoip.ll = lookup.ll;
      req.geoip.country.country_code = lookup.country;
      req.geoip.country.country_name = countryCodeToName[lookup.country];
      req.geoip.country.continent = countryCodeToContinent[lookup.country];
    }
    next();
  };
};

function getClientIp(req) {
  var ip_address = null;
  ip_address = req.headers['x-forwarded-for'];
  if (ip_address == undefined) {
    ip_address = req.connection.remoteAddress;
  } else {
    var ipParts = ip_address.split(', ');
    ip_address = ipParts[0];
  }

  return ip_address;
}